### ISSUE TITLE
如何配置其他频道

### ISSUE THREAD

**Issue by cmp0xff** [QuantumGhost/ncov-channel-crawler#1]
我们建立了一个跟疫情有关的侧重点不同的 Telegram 频道。请问是否能在文档中描述一下如何配置爬取的频道？感谢。

**Comment by shuiRong** [comment]
很简单，替换[代码中这里](https://github.com/QuantumGhost/ncov-channel-crawler/blob/222ca4bc97cc5365758351ff462773000b07763f/crawler/crawler.py#L38)的链接即可。

P.S. 我并非仓库的作者，仅靠开发者的直觉做的建议。（另外，希望你能将部署过程中遇到的坑记录下来，贴到这个issue即可）。

**Comment by QuantumGhost** [comment]
@cmp0xff 你只需要替换 https://github.com/QuantumGhost/ncov-channel-crawler/blob/222ca4bc97cc5365758351ff462773000b07763f/crawler/crawler.py#L39 这里的 channel_id 即可，channel_id 的获取可以通过 [get_entity](https://docs.telethon.dev/en/latest/modules/client.html#telethon.client.users.UserMethods.get_entity) 方法来进行（注意 get_entity 有相当严格的频率控制，这也是为什么我要写死 channel_id）

**Comment by shuiRong** [comment]
补充：获取频道ID还有个简单的方法， Telegram有个[bot](https://t.me/getidsbot)可以方便的给你返回各种ID。

P.S. 据观察频道ID前三位貌似固定有个`100`
![image](https://user-images.githubusercontent.com/16076993/75114700-52598080-5693-11ea-9887-e09b700fea44.png)
